### PR TITLE
ghc 8.8 compatibility

### LINKED ISSUE #1: Build failure with ghc 8.8
ghc 8.8 & its corresponding `base` have finally finished extracting `fail` from `Monad`, which has resulted in a build failure:

```
Opentype/Fileformat/Name.hs:87:24: error:
    • No instance for (MonadFail (Either String))
        arising from a use of ‘fail’
    • In the second argument of ‘($)’, namely
        ‘fail "Unsupported name table format."’
      In a stmt of a 'do' block:
        when (version > 0) $ fail "Unsupported name table format."
      In the expression:
        do version <- index16 bs 0
           when (version > 0) $ fail "Unsupported name table format."
           len <- index16 bs 1
           storage <- index16 bs 2
           ....
   |
87 |   when (version > 0) $ fail "Unsupported name table format."
   |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

### PR DESCRIPTION
**Pull request by robrix**
This PR fixes a couple of errors (fallout from the `MonadFail` proposal) when building using ghc 8.8.

Fixes #1.

### CODE REVIEW

File: Opentype/Fileformat/Cmap.hs [hunk 1]
```diff
@@ -135,7 +134,7 @@ readCmapTable :: Strict.ByteString -> Either String CmapTable
 readCmapTable bs = do
   version <- index16 bs 0
   when (version /= 0) $
-    fail "unsupported cmap version."
+    Left "unsupported cmap version."
```
Comment (robrix) [inline Opentype/Fileformat/Cmap.hs:137]: `fail` is no longer a method of `Monad`, and there is no `MonadFail` instance for `Either String`.

File: Opentype/Fileformat/Cmap.hs [hunk 2]
```diff
@@ -166,16 +165,15 @@ readCmap bs_ = do
...
-      i -> fail $ "unsupported map encoding " ++ show i
+  case c of
+    0 -> getMap0 bs
+    2 -> getMap2 bs
+    4 -> getMap4 bs
+    6 -> getMap6 bs
+    8 -> getMap8 bs
+    10 -> getMap10 bs
+    12 -> getMap12 bs
+    i -> Left $ "unsupported map encoding " ++ show i
```
Comment (robrix) [inline Opentype/Fileformat/Cmap.hs:176]: 1. Eliminating a couple more uses of `fail`.

2. The `case` expression is already in `Either String` so I’ve removed the conversion & dedented.

File: Opentype/Fileformat/Cmap.hs [hunk 3]
```diff
@@ -259,7 +257,7 @@ putMap2 cmap = do
                      (fromIntegral hb `shift` 8 .|. 0xff) $
                      glyphMap cmap
             (fstCode, lstCode)
-              | M.null subMap = (0, -1)
+              | M.null subMap = (0, maxBound)
```
Comment (robrix) [inline Opentype/Fileformat/Cmap.hs:260]: This was fine at runtime but was the cause of an overflowing literal warning.

**Review by robrix — COMMENTED** [review]
Ready for review.
