### PR TITLE
Correct name record bounds checking

### LINKED ISSUE #3: Failure loading Bitstream Vera
Attempting to load the open source font Bitstream Vera fails with the following error:

```
user error: string storage bounds exceeded
```

I believe the problem is that the offset test incorrectly fails because the length of the bytestring for a nametable is greater than 2^16, and thus when it’s converted to `Word16`, it wraps around to a smaller value.

### PR DESCRIPTION
**Pull request by robrix**
- [ ] Depends on #2.
- [x] Fixes #3.

### CODE REVIEW

File: Opentype/Fileformat/Name.hs [hunk 1]
```diff
@@ -97,8 +97,8 @@ readNameTable bs = do
     Right (offset, len2, NameRecord pf enc lang nID)
   records2 <- for records $
     \(offset, len2, r) ->
-      if storage+offset+len2 > fromIntegral (Strict.length bs)
-        then Left "string storage bounds exceeded"
+      if fromIntegral (storage+offset+len2) > Strict.length bs
+        then Left $ "overflow error: name record in storage at (" <> show storage <> ") at offset (" <> show offset <> ") with length (" <> show len2 <> ") exceeds input length (" <> show (Strict.length bs) <> ")"
```
Comment (robrix) [inline Opentype/Fileformat/Name.hs:101]: 1. By converting the offsets to `Int` instead of converting the `ByteString` to `Word16`, we can deal with inputs longer than 2^16.

2. Possibly we should be converting the `storage`, `offset`, & `len2` variables to `Int` separately, rather than converting the sum. Similarly, we should maybe convert `offset` and `storage` before adding them in the argument to `Strict.drop`? I’m not sure of the precise semantics for these fields or whether their sums can overflow, tho.

3. I added a bunch of error details to debug this and I figured that might still be helpful context.
